version: 0.2

env:
  variables:
    SIGNUP_ROUTE: "v1/signup"
    VERIFY_ROUTE: "v1/verify"
    SIGNIN_ROUTE: "v1/signin"
    SIGNOUT_ROUTE: "v1/signout"
    RESET_PASSWORD_ROUTE: "v1/reset-password"
    SOURCE_BUCKET_NAME: "source-bucket-s3bucket-1e6txaiywjvno"
    SIGNUP_SOURCE_KEY: "green-things-auth/v1/signup"
    VERIFY_SOURCE_KEY: "green-things-auth/v1/verify"
    SIGNIN_SOURCE_KEY: "green-things-auth/v1/signin"
    SIGNOUT_SOURCE_KEY: "green-things-auth/v1/signout"
    RESET_PASSWORD_SOURCE_KEY: "green-things-auth/v1/reset-password"
    TEMPLATE_PATH: "infrastructure/api.yml"
    STACK_NAME: "green-things-auth"
    SIGNUP_PARAMETER_NAME: "V1SignupSourceVersion"
    VERIFY_PARAMETER_NAME: "V1VerifySourceVersion"
    SIGNIN_PARAMETER_NAME: "V1SigninSourceVersion"
    SIGNOUT_PARAMETER_NAME: "V1SignoutSourceVersion"
    RESET_PASSWORD_PARAMETER_NAME: "V1ResetPasswordSourceVersion"

phases:
  install:
    commands:
      - ls
      - cd $CODEBUILD_SRC_DIR/src/utils/database
      - npm install
      - cd $CODEBUILD_SRC_DIR/src/$SIGNUP_ROUTE
      - npm install
      - cd $CODEBUILD_SRC_DIR/src/$VERIFY_ROUTE
      - npm install
      - cd $CODEBUILD_SRC_DIR/src/$SIGNIN_ROUTE
      - npm install
      #- cd $CODEBUILD_SRC_DIR/src/v1/signout
      #- npm install
      #- cd $CODEBUILD_SRC_DIR/src/v1/reset-password
      #- npm install
  build:
    commands:
      - cd $CODEBUILD_SRC_DIR
#
# Signup
#
      - mkdir $CODEBUILD_SRC_DIR/node_modules
      - rsync -a $CODEBUILD_SRC_DIR/src/$SIGNUP_ROUTE/node_modules/ $CODEBUILD_SRC_DIR/node_modules
      - rsync -a $CODEBUILD_SRC_DIR/src/utils/node_modules/ $CODEBUILD_SRC_DIR/node_modules
      - zip -r9 deployment-package $CODEBUILD_SRC_DIR/src/$SIGNUP_ROUTE/index.js $CODEBUILD_SRC_DIR/node_modules $CODEBUILD_SRC_DIR/src/utils &>/dev/null
      - aws s3 cp deployment-package.zip s3://$SOURCE_BUCKET_NAME/$SIGNUP_PARAMETER_NAME &>/dev/null
      - SIGNUP_S3_VERSION=$(aws s3api get-object --bucket $SOURCE_BUCKET_NAME --key $SIGNUP_PARAMETER_NAME getobjectoutfile | jq -r '.VersionId')
      - rm -rf $CODEBUILD_SRC_DIR/node_modules
#
# Verify
#
      - mkdir $CODEBUILD_SRC_DIR/node_modules
      # TODO uncomment following line if/when verify route has node_modules
      #- rsync -a $CODEBUILD_SRC_DIR/src/$VERIFY_ROUTE/node_modules/ $CODEBUILD_SRC_DIR/node_modules
      - rsync -a $CODEBUILD_SRC_DIR/src/utils/node_modules/ $CODEBUILD_SRC_DIR/node_modules
      - zip -r9 deployment-package $CODEBUILD_SRC_DIR/src/$VERIFY_ROUTE/index.js $CODEBUILD_SRC_DIR/node_modules $CODEBUILD_SRC_DIR/src/utils &>/dev/null
      - aws s3 cp deployment-package.zip s3://$SOURCE_BUCKET_NAME/$VERIFY_PARAMETER_NAME &>/dev/null
      - VERIFY_S3_VERSION=$(aws s3api get-object --bucket $SOURCE_BUCKET_NAME --key $VERIFY_PARAMETER_NAME getobjectoutfile | jq -r '.VersionId')
      - rm -rf $CODEBUILD_SRC_DIR/node_modules
#
# Signin
#
      - mkdir $CODEBUILD_SRC_DIR/node_modules
      - rsync -a $CODEBUILD_SRC_DIR/src/$SIGNIN_ROUTE/node_modules/ $CODEBUILD_SRC_DIR/node_modules
      - rsync -a $CODEBUILD_SRC_DIR/src/utils/node_modules/ $CODEBUILD_SRC_DIR/node_modules
      - zip -r9 deployment-package $CODEBUILD_SRC_DIR/src/$SIGNIN_ROUTE/index.js $CODEBUILD_SRC_DIR/node_modules $CODEBUILD_SRC_DIR/src/utils &>/dev/null
      - aws s3 cp deployment-package.zip s3://$SOURCE_BUCKET_NAME/$SIGNIN_PARAMETER_NAME &>/dev/null
      - SIGNIN_S3_VERSION=$(aws s3api get-object --bucket $SOURCE_BUCKET_NAME --key $SIGNIN_PARAMETER_NAME getobjectoutfile | jq -r '.VersionId')
      - rm -rf $CODEBUILD_SRC_DIR/node_modules
##
## Signout
##
#      - mkdir $CODEBUILD_SRC_DIR/node_modules
#      - rsync -a $CODEBUILD_SRC_DIR/src/$SIGNOUT_ROUTE/node_modules/ $CODEBUILD_SRC_DIR/node_modules
#      - rsync -a $CODEBUILD_SRC_DIR/src/utils/node_modules/ $CODEBUILD_SRC_DIR/node_modules
#      - zip -r9 deployment-package $CODEBUILD_SRC_DIR/src/$SIGNOUT_ROUTE/index.js $CODEBUILD_SRC_DIR/node_modules $CODEBUILD_SRC_DIR/src/utils &>/dev/null
#      - aws s3 cp deployment-package.zip s3://$SOURCE_BUCKET_NAME/$SIGNOUT_PARAMETER_NAME &>/dev/null
#      - SIGNOUT_S3_VERSION=$(aws s3api get-object --bucket $SOURCE_BUCKET_NAME --key $SIGNOUT_PARAMETER_NAME getobjectoutfile | jq -r '.VersionId')
#      - rm -rf $CODEBUILD_SRC_DIR/node_modules
##
## Reset Password
##
#      - mkdir $CODEBUILD_SRC_DIR/node_modules
#      - rsync -a $CODEBUILD_SRC_DIR/src/$RESET_PASSWORD_ROUTE/node_modules/ $CODEBUILD_SRC_DIR/node_modules
#      - rsync -a $CODEBUILD_SRC_DIR/src/utils/node_modules/ $CODEBUILD_SRC_DIR/node_modules
#      - zip -r9 deployment-package $CODEBUILD_SRC_DIR/src/$RESET_PASSWORD_ROUTE/index.js $CODEBUILD_SRC_DIR/node_modules $CODEBUILD_SRC_DIR/src/utils &>/dev/null
#      - aws s3 cp deployment-package.zip s3://$SOURCE_BUCKET_NAME/$RESET_PASSWORD_PARAMETER_NAME &>/dev/null
#      - RESET_PASSWORD_S3_VERSION=$(aws s3api get-object --bucket $SOURCE_BUCKET_NAME --key $RESET_PASSWORD_PARAMETER_NAME getobjectoutfile | jq -r '.VersionId')
#      - rm -rf $CODEBUILD_SRC_DIR/node_modules
post_build:
    commands:
      - aws cloudformation deploy --template-file $CODEBUILD_SRC_DIR/$TEMPLATE_PATH --stack-name $STACK_NAME --capabilities CAPABILITY_NAMED_IAM --parameter-overrides $SIGNUP_PARAMETER_NAME=$SIGNUP_S3_VERSION $VERIFY_PARAMETER_NAME=$VERIFY_S3_VERSION $SIGNIN_PARAMETER_NAME=$SIGNIN_S3_VERSION
      # $SIGNOUT_PARAMETER_NAME=$SIGNOUT_S3_VERSION $RESET_PASSWORD_PARAMETER_NAME=$RESET_PASSWORD_S3_VERSION
